export const Types = {
    UPDATE_NAME:'UPDATE_NAME',
    UPDATE_HEADER:'UPDATE_HEADER',
    UPDATE_BODY:'UPDATE_BODY',
    UPDATE_HOME:'UPDATE_HOME',
    UPDATE_HOMESECOND:'UPDATE_HOMESECOND',
    UPDATE_HOMETHIRD:'UPDATE_HOMETHIRD',
    UPDATE_FOOTER:'UPDATE_FOOTER',
    UPDATE_HEADER_COUNTRY: 'UPDATE_HEADER_COUNTRY',
    UPDATE_FOOTER_COUNTRY: 'UPDATE_FOOTER_COUNTRY'
};