export const Types = {
    UPDATE_NAME:'UPDATE_NAME',
    UPDATE_HEADER:'UPDATE_HEADER',
    UPDATE_BODY:'UPDATE_BODY',
    UPDATE_HOME:'UPDATE_HOME',
    UPDATE_HOMESECOND:'UPDATE_HOMESECOND',
    UPDATE_FOOTER:'UPDATE_FOOTER'
};